package: mediasort
version: 0.4.0
author: Adrian Kuehnis aku0112358@gmail.com
supportpage: https://github.com/akuehnis/redaxo5_addon_mediasort

pages:
    mediapool/mediasort:
        title: 'Media-Sort'
        perm: mediasort[]
        subpages:
          mediasort: { title: translate:mediasort, hidden: true}

requires:
    packages:
        media_manager: '^2.0.0'
    redaxo: ^5.0
